# Generated by Django 4.1.5 on 2023-01-13 03:51

from django.db import migrations, models
import transactions.models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to=transactions.models.file_generate_upload_path),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_type',
            field=models.CharField(choices=[('-', 'DEBIT'), ('+', 'CREDIT')], max_length=255),
        ),
    ]
