# Generated by Django 4.1.5 on 2023-01-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_balance_csv_file_alter_transaction_trans_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
