# Generated by Django 4.1.5 on 2023-01-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_balance_csv_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='trans_type',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(),
        ),
    ]
